### ISSUE TITLE
Migrate AppLayout

### ISSUE THREAD

**Issue by renoirb** [renoirb/renoirb-esm-modules#27]
From Nuxt project [renoirb/site](https://github.com/renoirb/site)

### Zone of the Sandwich Meat

```css
:host #__Layout { 
  contain: content; 
}
```

Or

```css
:host main.zone__sandwich__meat [part="slot-parent-default"] {
  contain: layout style;
} 
```

### \#__Layout

```css
:host main.zone__sandwich__meat [part="slot-parent-default"] {
  contain: layout style;
} 
```
